require("custom.remaps")
require("custom.set")
require("custom.colours")
require("custom.plugins.telescope")
require("custom.plugins.bufferline")
-- require("custom.plugins.nvim-tree")
require("custom.plugins.treesitter")
require("custom.plugins.treesitter-text")
require("custom.plugins.noice")
require("custom.plugins.copilot")
require("custom.plugins.leap")
require("custom.plugins.cmp")
require("custom.plugins.oil")
